// ── Nano Agent ──
// Lightweight ReAct (Reasoning + Acting) agent loop.
// Orchestrates: user input → LLM reasoning → tool calls → observation → final answer.

import type { LLMEngine, Message, GenerateOptions, ToolDefinition, ToolCall } from '@local-llm-agent/llm-engine';
import { countMessageTokens } from '@local-llm-agent/llm-engine';
import type { SkillDefinition, SkillParameter } from '@local-llm-agent/skill-store';
import type { ToolBridge, ToolResult } from '@local-llm-agent/tool-bridge';

/** Events emitted during agent execution */
export type AgentEvent =
  | { type: 'thinking'; content: string }
  | { type: 'tool_call'; tool: string; args: Record<string, unknown> }
  | { type: 'tool_result'; tool: string; result: ToolResult }
  | { type: 'token'; token: string }
  | { type: 'done'; response: string; steps: number }
  | { type: 'error'; error: string };

/** Configuration for the NanoAgent */
export interface NanoAgentConfig {
  engine: LLMEngine;
  toolBridge: ToolBridge;
  /** Maximum agent steps (tool call + response cycles) */
  maxSteps?: number;
  /** System prompt prepended to every conversation */
  systemPrompt?: string;
  /** LLM generation options */
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  /** Max context tokens before summarization */
  maxContextTokens?: number;
}

const DEFAULT_SYSTEM_PROMPT =
  'You are a helpful AI assistant running locally in the browser.';

/**
 * ReAct instructions appended to the system prompt WHEN tools are available.
 * Guides the model to reason first, then either call a tool or give a final
 * answer. Kept explicit and small so weak local models can follow it.
 */
const REACT_INSTRUCTIONS = `You can reason step by step and optionally use tools to help answer.

On each turn, respond in EXACTLY one of two ways:

1. To use a tool, output a single fenced code block with the tool call:
\`\`\`json
{ "name": "<tool_name>", "arguments": { "<arg>": "<value>" } }
\`\`\`

2. To answer the user directly (no tool needed, or after you have tool results),
   write your answer prefixed with "FINAL:" on its own, e.g.:
FINAL: <your concise answer here>

Rules:
- Think briefly about whether a tool is actually needed. If you already know the
  answer, just give the FINAL answer — do NOT call a tool unnecessarily.
- Use only the tools listed below, with valid arguments.
- After a tool runs, you will see its result; then either call another tool or
  give the FINAL answer.`;

export class NanoAgent {
  private engine: LLMEngine;
  private toolBridge: ToolBridge;
  private config: Required<Omit<NanoAgentConfig, 'engine' | 'toolBridge'>>;
  private messages: Message[] = [];
  private skills = new Map<string, SkillDefinition>();
  private _aborted = false;

  constructor(config: NanoAgentConfig) {
    this.engine = config.engine;
    this.toolBridge = config.toolBridge;
    this.config = {
      maxSteps: config.maxSteps ?? 5,
      systemPrompt: config.systemPrompt ?? DEFAULT_SYSTEM_PROMPT,
      temperature: config.temperature ?? 0.7,
      topP: config.topP ?? 0.9,
      maxTokens: config.maxTokens ?? 2048,
      maxContextTokens: config.maxContextTokens ?? 8192,
    };
  }

  /** Register a skill for the agent to use */
  registerSkill(skill: SkillDefinition): void {
    this.skills.set(skill.id, skill);
  }

  /** Register multiple skills */
  registerSkills(skills: SkillDefinition[]): void {
    for (const skill of skills) this.registerSkill(skill);
  }

  /** Get registered skills */
  getSkills(): SkillDefinition[] {
    return [...this.skills.values()];
  }

  /** Get the current conversation messages */
  getMessages(): Message[] {
    return [...this.messages];
  }

  /** Set conversation messages (e.g., restore from history) */
  setMessages(messages: Message[]): void {
    this.messages = [...messages];
  }

  /** Clear conversation history */
  clearHistory(): void {
    this.messages = [];
  }

  /** Run the agent on user input */
  async *run(input: string): AsyncIterable<AgentEvent> {
    this._aborted = false;

    // Add user message
    this.messages.push({ role: 'user', content: input });
    this._trimContext();

    let steps = 0;

    // Token sink: tokens generated by the engine are pushed here so we can
    // yield them as `token` events for live streaming in the UI.
    let tokenSink: string[] = [];

    while (steps < this.config.maxSteps && !this._aborted) {
      steps++;

      // Build system prompt with tool descriptions
      const tools = this._buildToolDefinitions();
      const systemPrompt = this._buildSystemPrompt(tools);

      // Prepare messages for LLM
      const generationMessages: Message[] = [
        { role: 'system', content: systemPrompt },
        ...this.messages,
      ];

      // Generate response
      tokenSink = [];
      const genOptions: GenerateOptions = {
        messages: generationMessages,
        temperature: this.config.temperature,
        topP: this.config.topP,
        maxTokens: this.config.maxTokens,
        tools: tools.length > 0 ? tools : undefined,
        onToken: (token) => {
          tokenSink.push(token);
        },
      };

      const result = await this.engine.generate(genOptions);
      const responseText = result.text;

      // Emit any buffered tokens for live streaming, then the settled text.
      for (const tok of tokenSink) {
        yield { type: 'token', token: tok };
      }
      tokenSink = [];

      // ── Decide: reason-only / tool call / final answer ──
      // Prefer the engine's parsed tool calls, but also robustly parse the raw
      // text ourselves so weaker models that don't emit perfect fences still work.
      const toolCalls =
        result.toolCalls && result.toolCalls.length > 0
          ? result.toolCalls
          : tools.length > 0
            ? this._parseToolCalls(responseText, tools)
            : [];

      // Reasoning text shown to the user is the response minus any tool JSON
      // and the FINAL marker.
      const reasoning = this._stripControlTokens(responseText);
      if (reasoning) {
        yield { type: 'thinking', content: reasoning };
      }

      // If the model emitted a valid tool call, execute it and loop again.
      const validCalls = toolCalls.filter((tc) => this.skills.has(tc.name));
      if (validCalls.length > 0) {
        for (const toolCall of validCalls) {
          yield { type: 'tool_call', tool: toolCall.name, args: toolCall.arguments };

          const toolResult = await this._executeTool(toolCall);
          yield { type: 'tool_result', tool: toolCall.name, result: toolResult };

          const formattedResult = this._formatToolResult(toolCall.name, toolResult);
          this.messages.push({
            role: 'assistant',
            content: reasoning || `Calling ${toolCall.name}`,
          });
          this.messages.push({
            role: 'tool',
            content: formattedResult,
            name: toolCall.name,
            toolCallId: toolCall.id,
          });
        }
        // Continue the reasoning loop with the observation(s) in context.
        continue;
      }

      // No tool call → this is the final answer. Strip a leading "FINAL:" marker.
      const finalText = this._extractFinal(responseText) || reasoning || responseText.trim();
      this.messages.push({ role: 'assistant', content: finalText });
      yield { type: 'done', response: finalText, steps };
      return;
    }

    // Max steps reached
    if (!this._aborted) {
      const finalMsg = 'I wasn\'t able to complete the task within the allowed steps. Please try a simpler query.';
      this.messages.push({ role: 'assistant', content: finalMsg });
      yield { type: 'done', response: finalMsg, steps };
    }
  }

  /** Abort the current agent run */
  abort(): void {
    this._aborted = true;
    this.engine.abort();
    this.toolBridge.abort();
  }

  // ── Private ──

  private _buildSystemPrompt(tools: ToolDefinition[]): string {
    let prompt = this.config.systemPrompt;

    if (tools.length > 0) {
      prompt += '\n\n' + REACT_INSTRUCTIONS;
      prompt += '\n\n## Available Tools\n\n';
      for (const tool of tools) {
        prompt += `### ${tool.function.name}\n`;
        prompt += `${tool.function.description}\n`;
        prompt += `Parameters: ${JSON.stringify(tool.function.parameters)}\n\n`;
      }
    }

    return prompt;
  }

  /**
   * Robustly parse tool calls from raw model output. Handles:
   *  - fenced ```json { "name": ..., "arguments": ... } ``` blocks
   *  - bare JSON objects containing a name/arguments (no fence)
   * Only returns calls whose name matches a known tool.
   */
  private _parseToolCalls(text: string, tools: ToolDefinition[]): ToolCall[] {
    const known = new Set(tools.map((t) => t.function.name));
    const calls: ToolCall[] = [];
    const seen = new Set<string>();

    const consider = (raw: string) => {
      let parsed: Record<string, unknown>;
      try {
        parsed = JSON.parse(raw);
      } catch {
        return;
      }
      const name = (parsed.name || parsed.tool || parsed.function) as string | undefined;
      if (!name || !known.has(name)) return;
      const args = (parsed.arguments || parsed.args || parsed.parameters || {}) as Record<
        string,
        unknown
      >;
      const key = name + JSON.stringify(args);
      if (seen.has(key)) return;
      seen.add(key);
      calls.push({
        id: `call_${Math.random().toString(36).slice(2, 9)}`,
        name,
        arguments: args,
      });
    };

    // 1) Fenced blocks.
    const fence = /```(?:json|tool_call)?\s*\n?(\{[\s\S]*?\})\s*```/g;
    let m: RegExpExecArray | null;
    let foundFence = false;
    while ((m = fence.exec(text)) !== null) {
      foundFence = true;
      consider(m[1]);
    }

    // 2) If no fenced call parsed, scan for bare balanced JSON objects that
    //    look like a tool call ("name" + arguments/args/parameters).
    if (!foundFence && calls.length === 0) {
      for (const candidate of this._extractJsonObjects(text)) {
        if (/"(name|tool|function)"\s*:/.test(candidate)) consider(candidate);
      }
    }

    return calls;
  }

  /** Extract top-level balanced {...} JSON substrings from text. */
  private _extractJsonObjects(text: string): string[] {
    const objects: string[] = [];
    let depth = 0;
    let start = -1;
    for (let i = 0; i < text.length; i++) {
      const c = text[i];
      if (c === '{') {
        if (depth === 0) start = i;
        depth++;
      } else if (c === '}') {
        if (depth > 0) {
          depth--;
          if (depth === 0 && start >= 0) {
            objects.push(text.slice(start, i + 1));
            start = -1;
          }
        }
      }
    }
    return objects;
  }

  /** Remove tool-call JSON blocks and the FINAL marker for display. */
  private _stripControlTokens(text: string): string {
    let out = text.replace(/```(?:json|tool_call)?\s*\n?\{[\s\S]*?\}\s*```/g, '').trim();
    // Drop a bare leading JSON tool-call object if present.
    out = out.replace(/^\s*\{[\s\S]*?"(name|tool|function)"[\s\S]*?\}\s*/i, '').trim();
    // Remove a leading FINAL: marker but keep the answer.
    out = out.replace(/^\s*FINAL\s*:\s*/i, '').trim();
    return out;
  }

  /** If the text contains a FINAL: answer, return just that answer. */
  private _extractFinal(text: string): string | null {
    const m = text.match(/FINAL\s*:\s*([\s\S]+)/i);
    if (!m) return null;
    // Also strip any trailing fenced blocks from the final answer.
    return m[1].replace(/```[\s\S]*?```/g, '').trim() || null;
  }

  private _buildToolDefinitions(): ToolDefinition[] {
    const tools: ToolDefinition[] = [];
    for (const skill of this.skills.values()) {
      tools.push({
        type: 'function',
        function: {
          name: skill.id,
          description: skill.description || skill.name,
          parameters: this._skillParamsToOpenAI(skill.tool.parameters || {}),
        },
      });
    }
    return tools;
  }

  private _skillParamsToOpenAI(params: Record<string, SkillParameter>): Record<string, unknown> {
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const [name, param] of Object.entries(params)) {
      properties[name] = {
        type: param.type,
        description: param.description,
      };
      if (param.enum) (properties[name] as any).enum = param.enum;
      if (param.required) required.push(name);
    }

    return {
      type: 'object',
      properties,
      ...(required.length > 0 ? { required } : {}),
    };
  }

  private async _executeTool(toolCall: ToolCall): Promise<ToolResult> {
    const skill = this.skills.get(toolCall.name);
    if (!skill) {
      return {
        success: false,
        error: `Unknown tool: ${toolCall.name}`,
        duration: 0,
      };
    }

    return this.toolBridge.execute(skill.tool, toolCall.arguments);
  }

  private _formatToolResult(name: string, result: ToolResult): string {
    if (!result.success) {
      return `Error executing ${name}: ${result.error}`;
    }

    const skill = this.skills.get(name);
    if (skill?.resultTemplate && result.data) {
      try {
        return this.toolBridge.applyTemplate(
          skill.resultTemplate,
          result.data as Record<string, unknown>,
          {} as any, // args already applied
        );
      } catch {
        // Fall back to JSON
      }
    }

    return JSON.stringify(result.data, null, 2);
  }

  private _trimContext(): void {
    // Ensure context doesn't exceed max tokens
    while (this.messages.length > 0) {
      const total = countMessageTokens(this.messages);
      if (total <= this.config.maxContextTokens) break;

      // Remove oldest non-system messages first
      const nonSystemIdx = this.messages.findIndex(m => m.role !== 'system');
      if (nonSystemIdx === -1) break;
      this.messages.splice(nonSystemIdx, 1);
    }
  }
}

/** Create a NanoAgent with default configuration */
export function createNanoAgent(config: NanoAgentConfig): NanoAgent {
  return new NanoAgent(config);
}
